version: '3.8'

services:
  stei-akademik-db:
    image: postgres:15-alpine
    container_name: election-arumba-db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - akademik-data:/var/lib/postgresql/data
    # networks:
    #   - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5 

volumes:
  akademik-data: