import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"

import { TRPCReactProvider } from "~/trpc/react";
import { NextAuthProvider } from "./session";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Pemilihan Pengurus Arumba Jabar",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
})
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
      <body>
        <TRPCReactProvider>
          <NextAuthProvider>
            {children}
            <Toaster />
          </NextAuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
